# -*- coding: utf-8 -*-
"""lab1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Gk0IBCTMpLcDPnAAqdS_Vh2j2DyrEgn

**Mohd Zain 22MT0214 Linear Regression**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from google.colab import files 
al=files.upload()

import io
df=pd.read_csv(io.BytesIO(al['lin_reg1.csv']))

df.head(5)

from sklearn.model_selection import train_test_split

X= df.iloc[:, :-1]
y = df.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=2, random_state=0)

from sklearn.linear_model import LinearRegression

lrg=LinearRegression()

lrg.fit(X_train,y_train)

y_pred=lrg.predict(X_test)
y_pred

lrg.score(X_test,y_test)#accuracy

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

mean_absolute_error(y_test,y_pred)

mean_squared_error(y_test,y_pred)

acc=r2_score(y_test,y_pred)

acc

print('your model accuracy is',round(acc*100,3),'%')

plt.scatter(y_test,y_pred);
plt.xlabel('Actual');
plt.ylabel('Predicted');

sns.regplot(x=y_test,y=y_pred,ci=None,color ='blue');