# -*- coding: utf-8 -*-
"""logreg.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eDQIQakJ8vBmZhGXaEK1CGq1LwOCH7Nx

**Mohd Zain 22MT0214 Logistic Regression**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from google.colab import files 
al=files.upload()

import io
df=pd.read_csv(io.BytesIO(al['Iris.csv']))

df.head(3)

df.tail(3)

df = df.drop(columns = ['Id'])
df.head(5)

df['Species'].value_counts()

df.corr()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Species'] = le.fit_transform(df['Species'])
df.head(100)

from sklearn.model_selection import train_test_split
X = df.drop(columns = ['Species'])
Y = df['Species']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train, Y_train)

Y_pred=model.predict(X_test)
Y_pred

from sklearn.metrics import r2_score

acc=r2_score(Y_test,Y_pred)
acc*100

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)
print(cm)

import seaborn as sns
ax=plt.axes()
df_cm=cm
sns.heatmap(df_cm, annot=True, annot_kws={"size": 30}, fmt='d',cmap="Blues", ax = ax )
ax.set_title('Confusion Matrix')
plt.show()