# -*- coding: utf-8 -*-
"""multivronhouse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19amFIPXMfBZqNl4E4q9ZVgBm2NdgMkAq

**22MT0214 Multivariate Linear Regression**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from google.colab import files 
al=files.upload()

import io
df=pd.read_csv(io.BytesIO(al['house.csv']))

df.head(3)

df.tail(3)

ds=df.sample(frac=1) #shuffling of data
ds.head()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import warnings
warnings.filterwarnings("ignore")

shape=ds.shape
print("Dataset contains {} rows and {} columns".format(shape[0],shape[1]))

x=ds.iloc[:,:3]
y=ds.iloc[:,3]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=2)

linreg=LinearRegression()
linreg.fit(x_train,y_train)

y_pred=linreg.predict(x_test)
y_pred

Accuracy=r2_score(y_test,y_pred)
Accuracy

percent=Accuracy*100
print('accuracy:',percent,'%')

from sklearn.metrics import mean_squared_error,mean_absolute_error
mean_squared_error(y_test,y_pred)

mean_absolute_error(y_test,y_pred)

plt.scatter(y_test,y_pred);
plt.xlabel('Actual');
plt.ylabel('Predicted');

sns.regplot(x=y_test,y=y_pred,ci=None,color ='blue');